Add URL decode func with tests

diff --git a/test/Makefile.am b/test/Makefile.am
--- a/test/Makefile.am
+++ b/test/Makefile.am
@@ -6,19 +6,26 @@ TESTS = \
 	unique_slug_02.sh \
 	unique_slug_03.sh \
 	unique_slug_04.sh \
-	unique_slug_05.sh
+	unique_slug_05.sh \
+	url_decode_01.sh \
+	url_decode_02.sh \
+	url_decode_03.sh
 
 
 
 check_PROGRAMS = \
-	uniqueslug
+	uniqueslug \
+	urldecode
 
 CLEANFILES = $(TESTS) \
 	out.txt \
-	uniqueslug
+	uniqueslug \
+	urldecode
 
 uniqueslug_LDADD = ../src/libcore.a
 uniqueslug_CPPFLAGS = -I$(top_srcdir)/src
+urldecode_LDADD = ../src/libcore.a
+urldecode_CPPFLAGS = -I$(top_srcdir)/src
 
 COMMON_ECHO = \
 	echo "export REQUEST_URI" >> $@ \
@@ -74,6 +81,18 @@ unique_slug_05.sh: uniqueslug
 	echo "./uniqueslug dog dog-10 dog dog-1 dog-2 dog-3 dog-4 dog-5 dog-6 dog-7 dog-8 dog-9 || exit 1" > $@
 	$(COMMON_POST_ECHO)
 
+
+url_decode_01.sh: urldecode
+	echo "./urldecode \"h%65%6C%6co\" hello || exit 1" > $@
+	$(COMMON_POST_ECHO)
+
+url_decode_02.sh: urldecode
+	echo "./urldecode \"http://dog?q=%63%61%6D%6f\" \"http://dog?q=camo\" || exit 1" > $@
+	$(COMMON_POST_ECHO)
+
+url_decode_03.sh: urldecode
+	echo "./urldecode \"h%65%6C%6\" hello || exit 0" > $@ # invalid input, expect failure
+	$(COMMON_POST_ECHO)
 
 
 
