Implement GET for a single todo

diff --git a/test/Makefile.am b/test/Makefile.am
--- a/test/Makefile.am
+++ b/test/Makefile.am
@@ -7,6 +7,8 @@ TESTS = \
 	test_case_143.sh \
 	test_case_145.sh \
 	test_case_160.sh \
+	test_case_200.sh \
+	test_case_210.sh \
 	test_case_900.sh \
 	unique_slug_01.sh \
 	unique_slug_02.sh \
@@ -139,6 +141,28 @@ test_case_160.sh:
 	$(DATA_TEST_INIT)
 	$(COMMON_ECHO)
 	echo "grep \"Status: 405 Method Not Allowed\" out.txt >/dev/null || exit 1" >> $@
+	$(COMMON_POST_ECHO)
+
+test_case_200.sh:
+	echo "REQUEST_BODY=data=My+t%65st%20message" > $@
+	echo "REQUEST_URI=/todos" >> $@
+	echo "REQUEST_METHOD=POST" >> $@
+	echo "CONTENT_TYPE=application/x-www-form-urlencoded" >> $@
+	$(DATA_TEST_INIT)
+	$(COMMON_ECHO)
+	echo "grep \"Status: 201 Created\" out.txt >/dev/null || exit 1" >> $@
+	echo "grep \"Location: /todos/my\" out.txt >/dev/null || exit 1" >> $@
+	echo "REQUEST_URI=/todos/my" >> $@
+	echo "REQUEST_METHOD=GET" >> $@
+	$(COMMON_ECHO)
+	echo "grep \"Status: 200 OK\" out.txt >/dev/null || exit 1" >> $@
+	$(COMMON_POST_ECHO)
+
+test_case_210.sh:
+	echo "REQUEST_URI=/todos/hey" > $@
+	echo "REQUEST_METHOD=GET" >> $@
+	$(COMMON_ECHO)
+	echo "grep \"Status: 404 File Not Found\" out.txt >/dev/null || exit 1" >> $@
 	$(COMMON_POST_ECHO)
 	
 test_case_900.sh:
